### ISSUE TITLE
A number of files are missing.

### ISSUE THREAD

**Issue by bulat1230** [quarpadd/diamondrp#1]
Hi, could you please upload all the files for this project? As you ordered, I assembled the project, started the server, but it turned out that there were not enough files such as: the "web" folder, /minigames and /phone files

**Comment by quarpadd** [comment]
Hi, sorry, let me see.

**Comment by bulat1230** [comment]
![image](https://user-images.githubusercontent.com/93978172/140907521-97335e1f-2bec-428c-9cf4-4174cb301bf4.png)
after starting the server, the error "missing file" is displayed in the upper left corner prone.html ", that is, it is not possible to open the phone, when you press the f2 button, nothing happens except for the gray window. I would be grateful if I could help solve these problems.

**Comment by quarpadd** [comment]
Pouring in the update.

**Comment by quarpadd** [comment]
Give me feedback please.

**Comment by bulat1230** [comment]
Yes, I'll take a look now and give you an answer

**Comment by bulat1230** [comment]
Thank you very much, everything worked.
